### ISSUE TITLE
Embedability - support postmessaging as an iframe

### ISSUE THREAD

**Issue by AmitMY** [Slevinski/signmaker#3]
SignMaker is probably the most powerful existing tool to write and edit signwriting, hands down.

I was trying to think about how to integrate with SignMaker to allow editing SignWriting, and I have a simple proposal.

In an app, one would create an iframe:
```html
<iframe src="http://slevinski.github.io/signmaker" />
```
Then, to that iframe, one could
```js
iframe.postMessage({'swu': '𝠃𝤓𝤕񀰂𝣹𝣷`})
```

SignMaker will receive this message, and update it's current view to edit that sign.

Then, an additional button should be added when it is an iframe - "done", which will:
```js
parent.postMessage({'swu': '...', 'fsw': '...'})
```

This communication will make SignMaker embeddable, and make any app using it very powerful.

**Comment by Slevinski** [comment]
Interesting idea.  I can take a look this weekend.

**Comment by Slevinski** [comment]
Great idea.  I forked this project and created [@sutton-signwriting/signmaker](https://github.com/sutton-signwriting/signmaker).  v1.0 is ready now.  v1.1 will be ready before 2022 starts.
